# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-11-27 03:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commit',
            name='parent_id',
        ),
        migrations.AddField(
            model_name='commit',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Commit'),
        ),
    ]
